-- =============================================================================
-- KISANSETU (SIH26032) - PHASE 22 SCHEMA ENHANCEMENTS
-- Team: ODE TO CODE
-- Description: Adds operational fields, stable sequence ordering, auditable
-- weighbridge logging, and explicit lifecycle status constraints.
-- =============================================================================

-- 1. Enhance Procurement Centres with real-time operational fields
ALTER TABLE public.procurement_centres
    ADD COLUMN IF NOT EXISTS operating_status VARCHAR(50) DEFAULT 'operational',
    ADD COLUMN IF NOT EXISTS current_load_percent INTEGER DEFAULT 75,
    ADD COLUMN IF NOT EXISTS delay_minutes INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS processing_rate_per_hour INTEGER DEFAULT 15;

-- 2. Enhance Queue Entries with stable sequence numbers
ALTER TABLE public.queue_entries
    ADD COLUMN IF NOT EXISTS sequence_number BIGINT GENERATED BY DEFAULT AS IDENTITY;

CREATE INDEX IF NOT EXISTS idx_queue_sequence ON public.queue_entries(sequence_number);

-- 3. Enhance Procurement Records with auditable weight change logs
ALTER TABLE public.procurement_records
    ADD COLUMN IF NOT EXISTS previous_weight NUMERIC(10, 2),
    ADD COLUMN IF NOT EXISTS weight_changed_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS weight_changed_by UUID REFERENCES auth.users(id),
    ADD COLUMN IF NOT EXISTS officer_notes TEXT;

-- 4. Ensure Bookings status constraint covers all 10 defined lifecycle states
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'chk_booking_lifecycle_status'
    ) THEN
        ALTER TABLE public.bookings
            ADD CONSTRAINT chk_booking_lifecycle_status
            CHECK (status IN (
                'BOOKED', 'APPROVED', 'CHECKED_IN', 'WAITING', 'PROCESSING',
                'COMPLETED', 'STANDBY', 'CANCELLED', 'EXPIRED', 'NO_SHOW',
                -- Also accept lowercase equivalents for backward compatibility
                'booked', 'approved', 'checked_in', 'waiting', 'processing',
                'completed', 'standby', 'cancelled', 'expired', 'no_show',
                'in_queue', 'procuring'
            ));
    END IF;
END $$;

-- 5. Ensure Payments status constraint covers all defined states
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'chk_payment_lifecycle_status'
    ) THEN
        ALTER TABLE public.payments
            ADD CONSTRAINT chk_payment_lifecycle_status
            CHECK (payment_status IN (
                'NOT_ELIGIBLE', 'PENDING', 'INITIATED', 'PROCESSING', 'SUCCESS', 'FAILED', 'REVERSED',
                -- Also accept title-case/lowercase for backward compatibility
                'not_eligible', 'pending', 'authorized', 'Authorized', 'processing', 'completed', 'Completed', 'failed'
            ));
    END IF;
END $$;
